<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,6,1,'5aWz6KOF');
$cfg_Cs[2]=array(1,6,1,'5LiK6KGj');
$cfg_Cs[3]=array(1,6,1,'6KOZ5a2Q');
$cfg_Cs[4]=array(0,6,1,'5aWz6Z6L');
$cfg_Cs[5]=array(4,6,1,'6auY5biu6Z6L');
$cfg_Cs[6]=array(4,6,1,'6Z205a2Q');
$cfg_Cs[7]=array(0,6,1,'5aWz5YyF');
$cfg_Cs[8]=array(7,6,1,'5rWB6IuP5YyF');
$cfg_Cs[9]=array(7,6,1,'5pac5oyO5YyF');
$cfg_Cs[10]=array(0,6,1,'5rS75Yqo');
$cfg_Cs[11]=array(0,1,1,'YmFubmVy');
?>