<li class="likes-li wfs">
					                        <span class="commend">[field:title/]</span>
					                        <a target="_blank" href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]"></a>
					                        <strong class="fl wfs" style="text-align: center;"><a title="[field:title/]" target="_blank" href="[field:arcurl/]">[field:title/]</a></strong>
					                        <i class="fl wfs">￥[field:trueprice/]元</i>
					                    </li>