<li class="items-li j-items-li">
                            <a target="_blank" href="[field:arcurl/]" style="position:relative;">
                                 <img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]">
                            </a>
                            <div class="wrap_div">
                                <div>
                               		<b class="title"><a target="_blank" href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></b>
                                    <span class="description">
                                      <a>[field:typeid function="GetTopTypename(@me)" /] </a>
                                      -
                                      <a href="[field:typeurl/]" title="[field:typename/]">[field:typename/]</a>
                                    </span>
                                    <p class="price-attente" ><a href="[field:tbk_link/]" target="_blank" style="padding:0 20px;background:#FC7878;color:#fff;">去购买</a></p>
                                </div>
                            </div>
                            <p class="price-attente">
                            
                              <span class="price"><span style="text-decoration:line-through;">￥[field:price/]</span> ￥[field:trueprice/]元 </span>
                              <span class="attente" title="浏览量">[field:click/]</span>
                            </p>
                        </li>