<div class="categorys-box fl wfs" style="border-left:0;">
                        <h4 class="title fl wfs">{dede:field.typename/}</h4><br>
                        <dl class="dl-categorys-item fl wfs">
                            {dede:channel type='sun'}
                            <dd class="dd-categorys-item">
                                <a target="_blank" href="[field:typeurl/]">[field:typename/]</a><br>
                            </dd>
                            {/dede:channel}
                        </dl>
                    </div>