<?php
$z[0]=Array("arcurl","",58,73);
$z[1]=Array("litpic","",188,203);
$z[2]=Array("litpic","",211,226);
$z[3]=Array("title","",233,247);
$z[4]=Array("arcurl","",397,412);
$z[5]=Array("title","",421,435);
$z[6]=Array("title","",453,467);
$z[7]=Array("typeid","",582,629);
$z[7][4]['function']="GetTopTypename(@me)";
$z[8]=Array("typeurl","",697,713);
$z[9]=Array("typename","",740,757);
$z[10]=Array("tbk_link","",853,870);
$z[11]=Array("price","",1137,1151);
$z[12]=Array("trueprice","",1162,1180);
$z[13]=Array("click","",1250,1264);

?>