<?php
$z[0]=Array("global","",106,138);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",739,771);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",1202,1234);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("channelartlist","\r\n                    <div class=\"categorys-box fl wfs\" style=\"border-left:0;\">\r\n                        <h4 class=\"title fl wfs\">{dede:field.typename/}</h4><br>\r\n                        <dl class=\"dl-categorys-item fl wfs\">\r\n                            {dede:channel type='sun'}\r\n                            <dd class=\"dd-categorys-item\">\r\n                                <a target=\"_blank\" href=\"[field:typeurl/]\">[field:typename/]</a><br>\r\n                            </dd>\r\n                            {/dede:channel}\r\n                        </dl>\r\n                    </div>\r\n                    ",1683,2346);
$z[3][4]['typeid']="1,4,7,10";
$z[4]=Array("global","",2553,2585);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("channel","\r\n            <a class=\"channel \" href=\"[field:typeurl/]\"  >[field:typename/]<span></span></a>\r\n            ",2802,3053);
$z[5][4]['type']="top";
$z[5][4]['row']="7";
$z[5][4]['currentstyle']="<a class='channel channel-now' href='~typelink~' >~typename~<span></span></a>";

?>